version: 2.1

parameters:
  action:
    type: enum
    enum: [check, run]
    default: run

jobs:
  check:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "check"

  run:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "run"
      - run: sleep 200


workflows:
  version: 2
  run_workflow:
      jobs:
          - run
      when:
          equal: [ run, << pipeline.parameters.action >> ]
  check_workflow:
      jobs:
          - check
      when:
          equal: [ check, << pipeline.parameters.action >> ]
